### ISSUE TITLE
i want to add tags(in articles resource, not in tags resource) when is not saved on 'tags' table in database.

### ISSUE THREAD

**Issue by Energon7** [palauaandsons/nova-tags-field#2]

**Comment by ipalaus** [comment]
This is a package to managed cartalyst/tags and won't support any other way of "adding tags".

Thanks

**Comment by tumainimosha** [comment]
@ipalaus thanks for the very helpful package.
I think this feature would be a good addition to the package. 
Adding tags on the fly from a Taggable resource add a lot of efficiency.
